export const CHANGE_BACKGROUND_TO_DARK = "CHANGE_BACKGROUND_TO_DARK"
export const CHANGE_BACKGROUND_TO_WHITE = "CHANGE_BACKGROUND_TO_WHITE"
export const CHANGE_COLOR_TO_DARK = "CHANGE_COLOR_TO_DARK";
export const CHANGE_COLOR_TO_WHITE = "CHANGE_COLOR_TO_WHITE";